backend:
  name: github
  repo: lawlimks/perfumeshots
  branch: main
  site_domain: perfumeshots.lawlimks.workers.dev

# Where uploaded images will be saved
media_folder: "assets/logos"
public_folder: "/assets/logos"

collections:
  - name: "site_data"
    label: "Site Data"
    delete: false
    files:
      - file: "data.json"
        label: "Perfumeshots Data"
        name: "data"
        file_kind: "json"
        fields:
          - label: "Brands"
            name: "brands"
            widget: "list"
            allow_add: true
            fields:
              - { label: "ID / Slug", name: "id", widget: "string" }
              - { label: "Brand Name", name: "name", widget: "string" }
              - { label: "Directory Checked Date", name: "directoryCheckedAt", widget: "string", required: false }
              - { label: "Website URL", name: "url", widget: "string", required: false }
              - { label: "Official Website", name: "website", widget: "string", required: false }
